#!/bin/bash

# function to check redis.conf config and bak
checkRedisConf() {
	if [[ $(cat /etc/redis/redis.conf) =~ "^\s*$" ]]; then
		mv /etc/redis/redis.conf.bak /etc/redis/redis.conf
	else
		rm /etc/redis/redis.conf.bak
	fi
}

#
# Set redis config variables
#
# REDIS_PROTECTED_MODE -> protected_mode
#
ENV_VARS=($(env))
for VAR in "${ENV_VARS[@]}"; do
	VAR_NAME=$(echo $VAR | cut -d'=' -f 1)
	VAR_VALUE=$(echo $VAR | cut -d'=' -f 2)
	if [[ "$VAR_NAME" =~ "REDIS_"* ]] && [[ "$VAR_NAME" != "REDIS_PORT" ]]; then
		REDIS_SETTING=$(echo $VAR_NAME | cut -d'_' -f 2-)
		REDIS_SETTING=$(echo $REDIS_SETTING | awk '{print tolower($0)}')
		REDIS_SETTING=$(echo $REDIS_SETTING | perl -pe "s/_/-/")
		perl -p -i.bak -e "s/^$REDIS_SETTING\s+.*/$REDIS_SETTING $VAR_VALUE/gi" /etc/redis/redis.conf
		checkRedisConf
	fi
done

# set redis listen port
perl -p -i.bak -e "s/port\s+(.+)/port $REDIS_PORT/gi" /etc/redis/redis.conf
checkRedisConf